info:
  component: Zuul Server
  
server:
  port: 8765
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

zuul:
  ignoredServices: "*"
  routes:
    composite:
      path: /composite-service/**
      serviceId: composite-service

