info:
  component: Eureka Server

server:
  port: 8761
  
eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
